import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex">
      <div className="flex flex-col w-[205px] h-screen">
        <div className="flex gap-3 mt-6 mb-7 mx-auto">
          <Image src="/logoHat.png" width={46} height={37} alt="logo" />
          <div className="flex flex-col">
            <div className="flex">
              <p className="text-black font-semibold text-xl">Nom</p>
              <p className="text-[#EF4444] font-semibold text-xl">Nom</p>
            </div>
            <p className="text-black text-xs">Swift delivery</p>
          </div>
        </div>
        <div className="flex flex-col gap-6 mx-auto">
          <Link href="/admin/menu">
            <Button> Food Menu</Button>
          </Link>
          <Link href="/admin/orders">
            <Button variant="ghost"> Orders</Button>
          </Link>
        </div>
      </div>

      {children}
    </div>
  );
}
